Redis:Endpoints: "localhost:6379"
Redis:Password: "rpassword"
Redis:SSL: "False"
Redis:TaskResultPrefix: "classification_task_result_"
RabbitMQ:HostName: "localhost"
RabbitMQ:Port: "5672"
RabbitMQ:UserName: "rmquser"
RabbitMQ:Password: "rmqpassword"
RabbitMQ:SSL_Enabled: "False"
RabbitMQ:QueueNames:CompletedClassificationTasks: "completed_classification_tasks_queue"
RabbitMQ:QueueNames:ClassificationTasks: "classification_tasks_queue"
Minio:Endpoint: "localhost:9000"
Minio:AccessKey: "muser"
Minio:SecretKey: "mpassword"
Minio:SSL: "False"
Minio:BucketNames:Images: "images-for-classification-tasks"
MLNet:ModelPath: "C:\\CodeProjects\\NET\\MaterialClassification/data/modelsWithImageClassification/model_withImageClassification_10_90_11.zip"